(() => {
  const $=id=>document.getElementById(id);
  const msg=(id,text,type='')=>{const e=$(id);if(e){e.textContent=text;e.className=`message ${type}`;}};
  function show(screen){$('login-screen').classList.toggle('hidden',screen!=='login');$('register-screen').classList.toggle('hidden',screen!=='register');}
  window.showAuth=()=>{$('app-container').classList.add('hidden');$('auth-container').classList.remove('hidden');show('login');};
  window.showApp=async()=>{$('auth-container').classList.add('hidden');$('app-container').classList.remove('hidden');try{await loadDashboardData();await loadClients();await loadTasks();await loadSalaryForm();await loadExpenses();await loadMovements();await loadObligations();installFinanceEnhancements();}catch(e){console.error(e);alert(e.message||'Could not load wallet data.');}};
  document.addEventListener('DOMContentLoaded',async()=>{
    $('show-register').onclick=()=>show('register');$('show-login').onclick=()=>show('login');$('btn-logout').onclick=async()=>{await supabaseClient.auth.signOut();showAuth();};
    $('login-form').onsubmit=async e=>{e.preventDefault();const b=$('btn-login');b.disabled=true;b.textContent='Signing in…';msg('login-message','');const r=await supabaseClient.auth.signInWithPassword({email:$('login-email').value.trim(),password:$('login-password').value});b.disabled=false;b.textContent='Sign In';if(r.error)msg('login-message',r.error.message,'error');};
    $('register-form').onsubmit=async e=>{e.preventDefault();const p=$('register-password').value;if(p!==$('register-confirm-password').value)return msg('register-message','Passwords do not match.','error');const r=await supabaseClient.auth.signUp({email:$('register-email').value.trim(),password:p});if(r.error)return msg('register-message',r.error.message,'error');if(r.data.session)showApp();else{show('login');msg('login-message','Account created. Check your email if confirmation is enabled.','success');}};
    const {data:{session}}=await supabaseClient.auth.getSession();if(session)showApp();else showAuth();
    supabaseClient.auth.onAuthStateChange((event,session)=>{if(session)showApp();else showAuth();});
  });
  function installFinanceEnhancements(){
    if(window.__financeEnhancementsInstalled)return;window.__financeEnhancementsInstalled=true;
    const tableLabels={clients:['Client','Net Budget','Collected','Client Owes','Work Remaining','Tasks','Actions'],tasks:['Task','Client','Value','Client Work Balance','Status','Actions'],salary:['Month','Amount','Status','Actions'],expenses:['Expense','Amount','Month','Status','Due','Actions'],movements:['Date','Type','Description','Amount','Status','Actions'],obligations:['Due','Title','Amount','Month','Status','Actions']};
    Object.entries(tableLabels).forEach(([name,labels])=>{const id={clients:'clients-table-body',tasks:'tasks-table-body',salary:'salary-history-body',expenses:'expenses-table-body',movements:'movements-table-body',obligations:'obligations-table-body'}[name];const tbody=$(id);if(!tbody)return;const apply=()=>tbody.querySelectorAll('tr').forEach(tr=>{Array.from(tr.children).forEach((td,i)=>{if(i<labels.length)td.dataset.label=labels[i];});if(name==='clients'&&tr.dataset.reportReady!=='1'&&!tr.querySelector('.client-report-btn')&&tr.children.length>=7&&!tr.querySelector('.empty')){const idFrom=tr.querySelector('[data-action="add-payment"]')?.dataset.id;if(idFrom){const actions=tr.lastElementChild;const b=document.createElement('button');b.className='btn secondary client-report-btn';b.dataset.action='client-report';b.dataset.id=idFrom;b.textContent='Report';actions.insertBefore(b,actions.firstChild);tr.dataset.reportReady='1';}}});};apply();new MutationObserver(apply).observe(tbody,{childList:true});});
    document.addEventListener('click',e=>{const b=e.target.closest('[data-action="client-report"]');if(b)openClientReport(b.dataset.id);});
  }
  async function openClientReport(clientId){
    try{
      const uid=(await supabaseClient.auth.getUser()).data?.user?.id;
      const [cr,pr,tr]=await Promise.all([supabaseClient.from('clients').select('*').eq('id',clientId).eq('user_id',uid).single(),supabaseClient.from('client_payments').select('*').eq('client_id',clientId).eq('user_id',uid).order('payment_date',{ascending:false}),supabaseClient.from('tasks').select('*').eq('client_id',clientId).eq('user_id',uid).order('created_at',{ascending:false})]);
      if(cr.error)throw cr.error;if(pr.error)throw pr.error;if(tr.error)throw tr.error;
      const c=cr.data,payments=pr.data||[],tasks=tr.data||[],net=c.currency==='USD'?Math.max(0,Number(c.total_budget||0)*Number(c.exchange_rate||1)-Number(c.transfer_fee_egp||0)):Number(c.total_budget||0),collected=payments.reduce((s,p)=>s+Number(p.amount_egp||0),0),taskTotal=tasks.reduce((s,t)=>s+Number(t.amount_egp??(t.currency==='USD'?Number(t.cost||0)*Number(t.exchange_rate||1):Number(t.cost||0)),0),taskTotal),owed=Math.max(0,net-collected),work=Math.max(0,net-taskTotal);
      const money=n=>`ج.م ${Number(n||0).toLocaleString('ar-EG',{minimumFractionDigits:2,maximumFractionDigits:2})}`,esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x])),fmt=d=>d?new Date(d).toLocaleDateString('en-GB'):'—';
      const taskRows=tasks.length?tasks.map(t=>`<div class="client-report-item"><div><strong>${esc(t.title)}</strong><small class="muted">${esc(t.status)} · ${fmt(t.created_at)}</small></div><strong>${money(t.amount_egp??(t.currency==='USD'?Number(t.cost||0)*Number(t.exchange_rate||1):Number(t.cost||0)))}</strong></div>`).join(''):'<p class="muted">No tasks recorded.</p>';
      const payRows=payments.length?payments.map(p=>`<div class="client-report-item"><div><strong>${fmt(p.payment_date)}</strong><small class="muted">${esc(p.notes||'Client payment')}</small></div><strong>${money(p.amount_egp)}</strong></div>`).join(''):'<p class="muted">No payments recorded.</p>';
      const html=`<div class="client-report"><div class="client-report-hero"><small>CLIENT FINANCIAL REPORT</small><h2>${esc(c.name)}</h2><p class="muted">${esc(c.currency)} · Budget ${esc(c.total_budget)} · Rate ${esc(c.exchange_rate)}</p></div><div class="client-report-kpis"><div class="client-report-kpi"><span>NET BUDGET</span><strong>${money(net)}</strong></div><div class="client-report-kpi"><span>COLLECTED</span><strong>${money(collected)}</strong></div><div class="client-report-kpi"><span>CLIENT OWES</span><strong>${money(owed)}</strong></div><div class="client-report-kpi"><span>WORK REMAINING</span><strong>${money(work)}</strong></div></div><div class="card"><h3>Tasks (${tasks.length})</h3><div class="client-report-list">${taskRows}</div></div><div class="card"><h3>Payments (${payments.length})</h3><div class="client-report-list">${payRows}</div></div><div class="report-actions"><button class="btn secondary" id="print-client-report">Print / Save PDF</button><button class="btn primary" id="close-client-report">Close</button></div><div class="client-report-print"><h1>${esc(c.name)} — Client Report</h1><p>Generated ${fmt(new Date())}</p><div class="print-grid"><div class="print-box"><span>Net Budget</span><strong>${money(net)}</strong></div><div class="print-box"><span>Collected</span><strong>${money(collected)}</strong></div><div class="print-box"><span>Client Owes</span><strong>${money(owed)}</strong></div><div class="print-box"><span>Work Remaining</span><strong>${money(work)}</strong></div></div><h2>Tasks</h2><table><thead><tr><th>Task</th><th>Status</th><th>Value</th></tr></thead><tbody>${tasks.map(t=>`<tr><td>${esc(t.title)}</td><td>${esc(t.status)}</td><td>${money(t.amount_egp??(t.currency==='USD'?Number(t.cost||0)*Number(t.exchange_rate||1):Number(t.cost||0)))}</td></tr>`).join('')}</tbody></table><h2>Payments</h2><table><thead><tr><th>Date</th><th>Notes</th><th>Amount</th></tr></thead><tbody>${payments.map(p=>`<tr><td>${fmt(p.payment_date)}</td><td>${esc(p.notes||'')}</td><td>${money(p.amount_egp)}</td></tr>`).join('')}</tbody></table></div></div>`;
      openModal(html);$('close-client-report').onclick=closeModal;$('print-client-report').onclick=()=>window.print();
    }catch(err){console.error(err);alert(err.message||'Could not build client report.');}
  }
})();