/* Finance/task balance fix v2 */
(function(){'use strict';
const M=a=>`ج.م ${Number(a||0).toLocaleString('ar-EG',{maximumFractionDigits:2})}`;
const C=(a,c)=>c==='USD'?`$${Number(a||0).toLocaleString('en-US',{maximumFractionDigits:2})}`:M(a);
const MON=()=>new Date().toISOString().slice(0,7);
const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]));
const taskEGP=t=>Number(t.amount_egp ?? (t.currency==='USD' ? Number(t.cost||0)*Number(t.exchange_rate||0) : Number(t.cost||0)));
const clientRate=c=>c.currency==='USD'?Number(c.exchange_rate||0):1;
const clientBudgetEGP=c=>Number(c.total_budget_egp ?? (Number(c.total_budget||0)*clientRate(c)));

async function getClientFix(id){const{data,error}=await supabaseClient.from('clients').select('*').eq('id',id).single();if(error)throw error;return data;}
async function tasksFor(ids){if(!ids.length)return{};const{data,error}=await supabaseClient.from('tasks').select('client_id,cost,currency,exchange_rate,amount_egp').in('client_id',ids);if(error)throw error;return(data||[]).reduce((o,t)=>{const k=t.client_id;o[k]??={egp:0,count:0};o[k].egp+=taskEGP(t);o[k].count++;return o},{});}
async function syncClientRemaining(c){const{data:ts,error}=await supabaseClient.from('tasks').select('cost,currency,exchange_rate,amount_egp').eq('client_id',c.id);if(error)throw error;const usedEgp=(ts||[]).reduce((s,t)=>s+taskEGP(t),0);const budgetEgp=clientBudgetEGP(c);const remEgp=Math.max(0,budgetEgp-usedEgp);const rate=clientRate(c);const remForeign=c.currency==='USD'&&rate>0?remEgp/rate:remEgp;const{error:e}=await supabaseClient.from('clients').update({remaining_budget:remForeign,remaining_budget_egp:remEgp}).eq('id',c.id);if(e)throw e;return{usedEgp,remEgp,remForeign,budgetEgp};}

async function loadClientsFix(){const{data,error}=await supabaseClient.from('clients').select('*').order('id',{ascending:false});if(error)return console.error(error);const totals=await tasksFor((data||[]).map(x=>x.id)),tb=document.getElementById('clients-table-body'),sel=document.getElementById('task-client-id');if(tb)tb.innerHTML='';if(sel)sel.innerHTML='<option value="">Select Client...</option>';let pending=0;(data||[]).forEach(c=>{const t=totals[c.id]||{egp:0,count:0},cc=c.currency==='USD'?'USD':'EGP',budget=Number(c.total_budget||0),budgetEgp=clientBudgetEGP(c),rate=clientRate(c),remainingEgp=Math.max(0,budgetEgp-t.egp),remaining=cc==='USD'&&rate>0?remainingEgp/rate:remainingEgp,col=Number(c.collected_amount||0),receivable=Math.max(0,budget-col);pending+=Math.max(0,Number(c.remaining_budget_egp??remainingEgp));if(tb)tb.innerHTML+=`<tr><td>${esc(c.name)}</td><td><strong>${C(budget,cc)}</strong><small class="movement-description">${M(budgetEgp)} net after fee</small></td><td><strong>${C(col,cc)}</strong><small class="movement-description">Actually collected</small></td><td><strong>${C(remaining,cc)}</strong><small class="movement-description">${M(remainingEgp)} remaining after tasks</small></td><td><strong>${C(cc==='USD'&&rate>0?t.egp/rate:t.egp,cc)}</strong><small class="movement-description">${M(t.egp)} · ${t.count} task(s)</small></td><td><span class="status-badge ${c.delivery_status==='delivered'?'collected':'pending'}">${esc(c.delivery_status||'not_started')}</span></td><td>${receivable>0?`<button class="btn btn-primary btn-sm" onclick="collectClientIncome(${c.id},${receivable},${receivable*rate},'${cc}')">Collect</button>`:'<span style="color:var(--text-secondary);font-size:12px">Fully collected</span>'}<button class="btn btn-secondary btn-sm" style="width:auto" onclick="deleteClient(${c.id})">Delete</button></td></tr>`;if(sel)sel.innerHTML+=`<option value="${c.id}">${esc(c.name)} — ${C(remaining,cc)} left</option>`;});const p=document.getElementById('total-pending-income');if(p)p.textContent=M(pending);}

async function loadTasksFix(){const{data,error}=await supabaseClient.from('tasks').select('*,clients(name,total_budget,total_budget_egp,currency,exchange_rate)').order('id',{ascending:false});if(error)return console.error(error);const sums={};(data||[]).forEach(t=>sums[t.client_id]=(sums[t.client_id]||0)+taskEGP(t));const tb=document.getElementById('tasks-table-body');if(!tb)return;tb.innerHTML='';(data||[]).forEach(t=>{const cc=t.clients?.currency==='USD'?'USD':'EGP',rate=cc==='USD'?Number(t.clients?.exchange_rate||0):1,budgetEgp=Number(t.clients?.total_budget_egp??Number(t.clients?.total_budget||0)*rate),usedEgp=sums[t.client_id]||0,remEgp=Math.max(0,budgetEgp-usedEgp),rem=cc==='USD'&&rate>0?remEgp/rate:remEgp;tb.innerHTML+=`<tr><td>${esc(t.title)}</td><td>${esc(t.clients?.name||'N/A')}</td><td><strong>${C(t.cost,t.currency==='USD'?'USD':'EGP')}</strong><small class="movement-description">${M(taskEGP(t))} EGP</small></td><td><span style="color:${t.status==='completed'?'var(--accent)':'orange'}">${t.status==='completed'?'Completed':'Pending'}</span></td><td><small class="movement-description">Client remaining: ${C(rem,cc)}</small>${t.status!=='completed'?`<button class="btn btn-primary btn-sm" onclick="completeTask('${t.id}')">Complete</button>`:''}<button class="btn btn-secondary btn-sm" onclick="deleteTask('${t.id}')">Delete</button></td></tr>`;});}

function taskUI(){const f=document.getElementById('form-task');if(!f||document.getElementById('task-currency'))return;const w=document.createElement('div');w.className='form-row';w.innerHTML='<div class="form-group"><label>Currency</label><select id="task-currency"><option value="EGP">جنيه مصري (EGP)</option><option value="USD">دولار أمريكي (USD)</option></select></div><div class="form-group" id="task-rate-wrap" style="display:none"><label>USD → EGP rate</label><input id="task-exchange-rate" type="number" step="0.0001" min="0"></div>';f.insertBefore(w,f.querySelector('.modal-actions'));document.getElementById('task-currency').onchange=async e=>{const usd=e.target.value==='USD';document.getElementById('task-rate-wrap').style.display=usd?'':'none';if(usd&&typeof fetchUsdEgpRate==='function')try{document.getElementById('task-exchange-rate').value=Number((await fetchUsdEgpRate(false)).rate).toFixed(4)}catch(_){};};}

async function saveTaskFix(e){e.preventDefault();e.stopImmediatePropagation();const clientId=document.getElementById('task-client-id').value,title=document.getElementById('task-title').value.trim(),cost=Number(document.getElementById('task-cost').value),cc=document.getElementById('task-currency')?.value||'EGP';let rate=Number(document.getElementById('task-exchange-rate')?.value||0);if(!clientId||!title||!Number.isFinite(cost)||cost<=0)return alert('Enter a valid client, title and task value.');if(cc==='USD'){if(!rate&&typeof fetchUsdEgpRate==='function')try{rate=Number((await fetchUsdEgpRate(false)).rate)}catch(_){}if(!rate)return alert('A valid USD → EGP rate is required.')}else rate=1;const c=await getClientFix(clientId),before=await syncClientRemaining(c);const egp=cost*rate;if(before.usedEgp+egp>before.budgetEgp+1e-6)return alert(`Task exceeds client budget. Remaining: ${M(before.remEgp)}`);const u=(await supabaseClient.auth.getUser()).data?.user,row={client_id:clientId,title,cost,currency:cc,exchange_rate:rate,amount_egp:egp,status:'pending'};if(u?.id)row.user_id=u.id;const{error:er}=await supabaseClient.from('tasks').insert([row]);if(er)return alert(er.message);await syncClientRemaining(c);fReset();await loadTasksFix();await loadClientsFix();if(typeof loadDashboardData==='function')await loadDashboardData();}
function fReset(){const f=document.getElementById('form-task');if(f)f.reset();if(document.getElementById('task-rate-wrap'))document.getElementById('task-rate-wrap').style.display='none';if(typeof closeModal==='function')closeModal('modal-task');}
async function completeFix(id){const{data,error}=await supabaseClient.from('tasks').select('id,status').eq('id',id).single();if(error||!data)return;if(data.status==='completed')return;const{error:e}=await supabaseClient.from('tasks').update({status:'completed',completed_at:new Date().toISOString()}).eq('id',id);if(e)return alert(e.message);await loadTasksFix();await loadClientsFix();if(typeof loadDashboardData==='function')await loadDashboardData();}
async function deleteTaskFix(id){if(!confirm('Delete task? Its value will immediately return to the client remaining budget.'))return;const{data:t,error:getErr}=await supabaseClient.from('tasks').select('client_id').eq('id',id).single();if(getErr)return alert(getErr.message);const{error}=await supabaseClient.from('tasks').delete().eq('id',id);if(error)return alert(error.message);const c=await getClientFix(t.client_id);await syncClientRemaining(c);await loadTasksFix();await loadClientsFix();if(typeof loadDashboardData==='function')await loadDashboardData();}

async function collectFix(id){const c=await getClientFix(id),old=Number(c.collected_amount||0),max=Math.max(0,Number(c.total_budget||0)-old),amt=Number(prompt(`Amount to collect (remaining: ${C(max,c.currency)})`,max));if(!Number.isFinite(amt)||amt<=0||amt>max)return;const rate=c.currency==='USD'?Number(c.exchange_rate||0):1;const{error:p}=await supabaseClient.from('client_payments').insert([{client_id:id,user_id:(await supabaseClient.auth.getUser()).data?.user?.id||null,amount:amt,currency:c.currency||'EGP',exchange_rate:rate,amount_egp:amt*rate,month_year:MON(),collected_at:new Date().toISOString()}]);if(p)return alert(p.message);const n=old+amt,{error}=await supabaseClient.from('clients').update({collected_amount:n,is_collected:n>=Number(c.total_budget)}).eq('id',id);if(error)return alert(error.message);await syncClientRemaining(c);await loadClientsFix();if(typeof loadDashboardData==='function')await loadDashboardData();}

async function adjustments(m){const{data}=await supabaseClient.from('balance_adjustments').select('amount').eq('month_year',m);return(data||[]).reduce((s,x)=>s+Number(x.amount||0),0)}
async function payments(m){const{data,error}=await supabaseClient.from('client_payments').select('amount_egp').eq('month_year',m);return error?[]:(data||[])}
async function paidExpenses(m){const a=await supabaseClient.from('expenses').select('amount').eq('month_year',m).eq('is_paid',true),b=await supabaseClient.from('daily_expenses').select('amount').gte('created_at',m+'-01').lt('created_at',m+'-32');return{fixed:(a.data||[]).reduce((s,x)=>s+Number(x.amount||0),0),daily:(b.data||[]).reduce((s,x)=>s+Number(x.amount||0),0),recurring:typeof recurringPaidExpensesTotal==='function'?recurringPaidExpensesTotal(m):0}}
async function loadDashFix(){const m=MON(),[{data:s},p,e,a]=await Promise.all([supabaseClient.from('salaries').select('amount').eq('month_year',m).eq('is_received',true),payments(m),paidExpenses(m),adjustments(m)]),ms=typeof getMovementSummary==='function'?getMovementSummary():{cashImpact:0,heldCustomerFunds:0,loansOutstanding:0,obligations:0},salary=(s||[]).reduce((x,y)=>x+Number(y.amount||0),0),client=(p||[]).reduce((x,y)=>x+Number(y.amount_egp||0),0),movement=typeof readMovements==='function'?readMovements().filter(x=>String(x.createdAt||'').slice(0,7)===m).reduce((x,y)=>x+(typeof getMovementCashImpact==='function'?getMovementCashImpact(y):0),0):0,available=salary+client+a+movement-e.fixed-e.daily-e.recurring;const set=(id,v)=>{const x=document.getElementById(id);if(x)x.textContent=M(v)};set('dash-salary',salary);set('dash-clients-income',client);set('dash-expenses',e.fixed+e.recurring);set('dash-daily-expenses',e.daily);set('dash-available',available);set('dash-held-funds',ms.heldCustomerFunds);set('dash-loans-outstanding',ms.loansOutstanding);set('dash-obligations',ms.obligations);}
async function reportFix(){const m=document.getElementById('report-month')?.value||MON(),r=document.getElementById('report-results');if(!r)return;const[s,p,e,a]=await Promise.all([supabaseClient.from('salaries').select('amount').eq('month_year',m).eq('is_received',true),payments(m),paidExpenses(m),adjustments(m)]),salary=(s.data||[]).reduce((x,y)=>x+Number(y.amount||0),0),client=(p||[]).reduce((x,y)=>x+Number(y.amount_egp||0),0),net=salary+client+a-e.fixed-e.daily-e.recurring;r.innerHTML=`<h3>Financial report — ${esc(m)}</h3><p><strong>Confirmed salary:</strong> ${M(salary)}</p><p><strong>Client payments collected this month:</strong> ${M(client)}</p><p><strong>Manual cash adjustments:</strong> ${M(a)}</p><p><strong>Paid fixed expenses:</strong> ${M(e.fixed+e.recurring)}</p><p><strong>Daily expenses:</strong> ${M(e.daily)}</p><hr><p class="report-total"><strong>Net cash for month:</strong> ${M(net)}</p>`}
function intercept(){document.addEventListener('submit',e=>{if(e.target?.id==='form-task'){saveTaskFix(e)}},true);document.addEventListener('submit',e=>{if(e.target?.id==='form-adjust-available'){e.preventDefault();e.stopImmediatePropagation();const n=Number(document.getElementById('custom-available-input')?.value);if(Number.isFinite(n)){supabaseClient.from('balance_adjustments').insert([{amount:n,month_year:MON(),created_at:new Date().toISOString()}]).then(({error})=>error?alert(error.message):loadDashFix())}e.target.reset()}},true);}
function init(){taskUI();intercept();window.loadClients=loadClientsFix;window.loadTasks=loadTasksFix;window.completeTask=completeFix;window.deleteTask=deleteTaskFix;window.collectClientIncome=collectFix;window.generateReport=reportFix;window.setAvailableBalance=async v=>{const n=Number(v);if(!Number.isFinite(n))return;const{error}=await supabaseClient.from('balance_adjustments').insert([{amount:n,month_year:MON(),created_at:new Date().toISOString()}]);if(error)alert(error.message);else loadDashFix()};const h=document.querySelector('#form-adjust-available')?.closest('.auth-card')?.previousElementSibling?.querySelector('h3');if(h)h.textContent='Manual Cash Adjustment';loadClientsFix();loadTasksFix();loadDashFix();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();