// ==========================================
// إدارة الواجهة (UI Navigation & Modals)
// ==========================================
const navItems=document.querySelectorAll('.nav-item');
const contentSections=document.querySelectorAll('.content-section');
const appSidebar=document.getElementById('app-sidebar');
const mobileMenuToggle=document.getElementById('mobile-menu-toggle');
const mobileNavOverlay=document.getElementById('mobile-nav-overlay');
function setMobileMenu(open){if(!appSidebar||!mobileMenuToggle)return;const o=Boolean(open);appSidebar.classList.toggle('mobile-menu-open',o);appSidebar.setAttribute('aria-hidden',String(!o));mobileMenuToggle.setAttribute('aria-expanded',String(o));mobileMenuToggle.setAttribute('aria-label',o?'Close navigation menu':'Open navigation menu');const i=mobileMenuToggle.querySelector('i');if(i){i.classList.toggle('fa-bars',!o);i.classList.toggle('fa-xmark',o)}if(mobileNavOverlay){mobileNavOverlay.classList.toggle('hidden',!o);mobileNavOverlay.setAttribute('aria-hidden',String(!o))}document.body.classList.toggle('mobile-nav-is-open',o)}
setMobileMenu(false);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&appSidebar?.classList.contains('mobile-menu-open')){setMobileMenu(false);mobileMenuToggle?.focus()}});mobileMenuToggle?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();setMobileMenu(!appSidebar?.classList.contains('mobile-menu-open'))});mobileNavOverlay?.addEventListener('click',()=>setMobileMenu(false));navItems.forEach(item=>item.addEventListener('click',()=>{navItems.forEach(n=>n.classList.remove('active'));item.classList.add('active');contentSections.forEach(s=>s.classList.add('hidden'));const id=item.getAttribute('data-target');document.getElementById(id)?.classList.remove('hidden');if(typeof refreshSectionData==='function')refreshSectionData(id);setMobileMenu(false)}));window.addEventListener('resize',()=>{if(innerWidth>768)setMobileMenu(false)});window.setMobileMenu=setMobileMenu;
function setupModal(openBtnId,modalId){const b=document.getElementById(openBtnId),m=document.getElementById(modalId);if(!b||!m)return;b.addEventListener('click',()=>m.classList.remove('hidden'));m.querySelectorAll('.close-modal').forEach(x=>x.addEventListener('click',()=>m.classList.add('hidden')));m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')})}setupModal('open-add-client-modal','modal-client');setupModal('open-add-task-modal','modal-task');setupModal('open-add-expense-modal','modal-expense');setupModal('open-add-movement-modal','modal-movement');function closeModal(id){document.getElementById(id)?.classList.add('hidden')}
window.addEventListener('load',()=>{const s=document.createElement('script');s.src='js/finance-fixes.js?v=20260829-3';s.onload=()=>{const p=document.createElement('script');p.src='js/finance-fixes-patch.js?v=20260829-3';p.onload=()=>{const r=document.createElement('script');r.src='js/finance-report-fix.js?v=20260829-1';r.onload=()=>{const c=document.createElement('script');c.src='js/finance-consistency-fix.js?v=20260829-1';c.onload=()=>{const a=document.createElement('script');a.src='js/finance-available-fix.js?v=20260829-2';document.body.appendChild(a)};document.body.appendChild(c)};document.body.appendChild(r)};document.body.appendChild(p)};document.body.appendChild(s)},{once:true});